[project]
name = "gpt-el"
version = "2.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.42.0",
    "openai>=1.58.1",
    "google-genai>=1.10.0",
    "jsonlines>=3.0.0",
]
